try workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,8 +23,16 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }} # 使用 GitHub Secrets 中的 Docker Hub 用户名
           password: ${{ secrets.DOCKER_PASSWORD }} # 使用 GitHub Secrets 中的 Docker Hub 密码
 
+      - name: Check if JAR file exists
+        run: |
+          ls -l ./target/pricehub-backend-1.0-SNAPSHOT.jar
+          if [ ! -f ./target/pricehub-backend-1.0-SNAPSHOT.jar ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
+
       # 3. 构建并推送 pri.server 镜像
-      - name: Build and push pri.server
+      - name: Build and push pricehub.server
         uses: docker/build-push-action@v2
         with:
           context: server # 构建上下文为 server 目录
@@ -32,7 +40,7 @@ jobs:
           tags: thorin215/pricehub.server:latest # 镜像标签
 
       # 4. 构建并推送 application.web 镜像
-      - name: Build and push application.web
+      - name: Build and push pricehub.web
         uses: docker/build-push-action@v2
         with:
           context: web # 构建上下文为 web 目录
